version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
  pg:
    image: postgres:14-alpine
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=csc791
  flask:
    build: core
    volumes:
      - ./core/src:/src
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      TMDB_API_KEY: 156816b2b0c708e0e8a9828552095eb7
    depends_on:
      - redis
      - pg

volumes:
  pg_data: